import type { QuizTemplate, QuizStep, QuizChoice, RecommendationTag } from '@/lib/db/types';

// Helper to create quiz steps with consistent tag structure
const createChoice = (
  id: string,
  text: string,
  feedback: string,
  tagEffects: Record<RecommendationTag, number>,
  complexity?: 'basic' | 'intermediate' | 'advanced'
): QuizChoice => ({
  id,
  text,
  feedback,
  tagEffects,
  complexity,
});

const createStep = (
  stepNumber: number,
  scenario: string,
  question: string,
  choices: QuizChoice[]
): QuizStep => ({
  id: `step_${stepNumber}`,
  stepNumber,
  scenario,
  question,
  choices,
});

// FIELD 1: SOFTWARE ENGINEER
// L1: Your First Day
const softwareEngineer_L1: QuizTemplate = {
  id: '', // Will be generated by DB
  field_id: 'software-engineer',
  level: 1,
  title: 'Your First Day as a Junior Engineer',
  description: 'You just started at a tech company. Navigate your first day and learn the basics of software development.',
  difficulty_level: 'basic',
  quiz_data: {
    steps: [
      createStep(
        1,
        'Your onboarding meeting just ended. The team is about to start their standup, and your mentor mentions you can either sit in or spend time setting up your dev environment.',
        'What do you do?',
        [
          createChoice(
            'c1',
            'Join the standup to understand what the team is working on',
            'Good choice! Understanding team context helps you learn faster, though setup takes time.',
            { analytical: 1, social: 2, creative: 0, hands_on: 0, problem_solving: 0 }
          ),
          createChoice(
            'c2',
            'Skip it and focus on getting your development environment ready',
            'Smart—being prepared to code is important, but missing context about ongoing work.',
            { analytical: 1, hands_on: 2, creative: 0, social: -1, problem_solving: 0 }
          ),
          createChoice(
            'c3',
            'Ask your mentor which would be more helpful',
            'Great question! Showing initiative and seeking guidance.',
            { social: 2, problem_solving: 1, analytical: 0, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        2,
        'During code review, you spot a potential bug in someone else\'s code. Your mentor says you could mention it now or wait until you\'re more familiar with the codebase.',
        'How do you handle it?',
        [
          createChoice(
            'c1',
            'Speak up immediately with your observation',
            'Bold move! Shows attention to detail, but you might misunderstand context.',
            { analytical: 2, problem_solving: 1, creative: 0, hands_on: 0, social: -1 }
          ),
          createChoice(
            'c2',
            'Keep quiet and ask your mentor about it privately later',
            'Diplomatic. You learn more before giving feedback.',
            { social: 1, analytical: 1, creative: 0, hands_on: 0, problem_solving: 0 }
          ),
          createChoice(
            'c3',
            'Ask a clarifying question to understand the code better first',
            'Perfect balance—learning while showing engagement.',
            { analytical: 2, social: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        3,
        'You\'re assigned your first ticket: fix a small bug in the authentication module. The code is complex, and you\'re not sure where to start.',
        'What\'s your approach?',
        [
          createChoice(
            'c1',
            'Dive in and try different things until something works',
            'Shows initiative, but might create more problems.',
            { hands_on: 2, problem_solving: 0, analytical: -1, creative: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Read through all the documentation before writing any code',
            'Thorough, but could take a long time.',
            { analytical: 2, creative: 0, hands_on: 0, problem_solving: 0, social: 0 }
          ),
          createChoice(
            'c3',
            'Ask your mentor to walk you through the code structure first',
            'Smart! Getting guidance saves time and prevents mistakes.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        4,
        'A senior engineer pushes back on your code during review, saying it\'s not following team standards. You don\'t fully understand their feedback.',
        'How do you respond?',
        [
          createChoice(
            'c1',
            'Ask them to explain which standards and why they matter',
            'Excellent—seeking to understand improves both your code and relationship.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Defensively explain why you wrote it that way',
            'Risky. Could damage your relationship with the senior engineer.',
            { social: -1, analytical: 0, creative: 0, hands_on: 0, problem_solving: 0 }
          ),
          createChoice(
            'c3',
            'Just rewrite it however they suggest without asking questions',
            'Compliant, but you miss learning the "why."',
            { hands_on: 1, social: 1, analytical: -1, creative: -1, problem_solving: 0 }
          ),
        ]
      ),
      createStep(
        5,
        'By end of day, you\'ve completed your first ticket. A teammate invites you to grab coffee and chat informally about the role.',
        'Do you go?',
        [
          createChoice(
            'c1',
            'Absolutely—building relationships with teammates is important',
            'Great! Team connections are valuable for learning and growth.',
            { social: 2, creative: 0, analytical: 0, hands_on: 0, problem_solving: 0 }
          ),
          createChoice(
            'c2',
            'Politely decline and review your code changes instead',
            'Focused, but team bonds help long-term.',
            { analytical: 1, hands_on: 1, social: -1, creative: 0, problem_solving: 0 }
          ),
          createChoice(
            'c3',
            'Go but keep it brief so you can keep working',
            'Balanced approach.',
            { social: 1, analytical: 0, creative: 0, hands_on: 1, problem_solving: 0 }
          ),
        ]
      ),
      createStep(
        6,
        'Your manager asks how your first day was and if you have any concerns. The codebase is bigger than you expected.',
        'What do you say?',
        [
          createChoice(
            'c1',
            'Say everything is great and you\'re handling it fine',
            'Polite but dishonest. Misses a chance for support.',
            { social: 1, analytical: -1, creative: 0, hands_on: 0, problem_solving: -1 }
          ),
          createChoice(
            'c2',
            'Be honest that the codebase is overwhelming and you\'ll need time to ramp up',
            'Transparent and professional. Good feedback for your manager.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Ask for a list of specific resources or courses to get up to speed',
            'Proactive. Shows you\'re taking ownership of your learning.',
            { analytical: 2, problem_solving: 1, social: 1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
    ],
    minMasteryScore: 75,
    estimatedTime: 8,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 8,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// L2: Shipping Your First Feature
const softwareEngineer_L2: QuizTemplate = {
  id: '',
  field_id: 'software-engineer',
  level: 2,
  title: 'Shipping Your First Feature',
  description: 'You\'ve been at the company for 3 months. Now you\'re taking ownership of a feature from start to finish.',
  difficulty_level: 'intermediate',
  quiz_data: {
    steps: [
      createStep(
        1,
        'During planning, the product manager describes a feature, but the timeline seems tight. You estimate it\'ll take 2 weeks; they want it in 1.',
        'How do you handle the gap?',
        [
          createChoice(
            'c1',
            'Agree to 1 week to prove yourself',
            'Shows ambition but sets yourself up for failure.',
            { problem_solving: -1, hands_on: 1, analytical: -1, creative: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Break down the feature into smaller parts and see what\'s possible in 1 week',
            'Smart approach—find what\'s achievable.',
            { analytical: 2, problem_solving: 2, creative: 1, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c3',
            'Push back strongly and insist on 2 weeks',
            'Transparent but maybe too rigid.',
            { analytical: 1, problem_solving: 0, social: -1, creative: -1, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        2,
        'Halfway through development, you realize the feature needs a database migration that could break existing data. This wasn\'t anticipated.',
        'What do you do?',
        [
          createChoice(
            'c1',
            'Work around it with a hacky solution to stay on schedule',
            'Risky—technical debt that\'ll bite you later.',
            { hands_on: 1, problem_solving: -1, analytical: -1, creative: 1, social: 0 }
          ),
          createChoice(
            'c2',
            'Stop and tell your manager about the blocker immediately',
            'Transparent, but maybe should explore first.',
            { social: 2, analytical: 1, problem_solving: 0, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Design a safe migration strategy and adjust the timeline accordingly',
            'Professional—solves the problem properly.',
            { analytical: 2, problem_solving: 2, hands_on: 1, creative: 0, social: 1 }
          ),
        ]
      ),
      createStep(
        3,
        'Your code review is thorough, and a senior engineer suggests a completely different architecture. You spent 3 days on the current approach.',
        'How do you react?',
        [
          createChoice(
            'c1',
            'Feel defensive but listen carefully to understand their reasoning',
            'Mature approach. Learning is more important than ego.',
            { analytical: 2, social: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Argue that your approach works and suggest merging anyway',
            'Risky. Worse code gets shipped.',
            { social: -1, analytical: 0, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Thank them for the feedback and offer to refactor if it significantly improves the design',
            'Balanced—values their input but also your time investment.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        4,
        'Testing reveals a bug in an edge case you didn\'t consider. The fix is quick but requires touching code you didn\'t write.',
        'How do you proceed?',
        [
          createChoice(
            'c1',
            'Make the fix yourself quickly without asking anyone',
            'Fast but risky if you break something else.',
            { hands_on: 2, problem_solving: 1, analytical: 0, creative: 0, social: -1 }
          ),
          createChoice(
            'c2',
            'Ask the original author\'s permission before changing their code',
            'Respectful, though might slow things down.',
            { social: 2, analytical: 1, problem_solving: 0, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Fix it yourself but message them after to explain what you changed and why',
            'Good balance—gets it done while respecting collaboration.',
            { analytical: 1, hands_on: 1, social: 1, problem_solving: 1, creative: 0 }
          ),
        ]
      ),
      createStep(
        5,
        'The feature is ready to ship, but your metrics dashboard shows it might slightly slow down page load times for 2% of users.',
        'What\'s your call?',
        [
          createChoice(
            'c1',
            'Ship it—2% is negligible',
            'Pragmatic, but might accumulate over time.',
            { problem_solving: 0, analytical: -1, creative: 0, hands_on: 1, social: 0 }
          ),
          createChoice(
            'c2',
            'Optimize first and delay the launch by a few days',
            'Quality-focused but maybe over-engineering.',
            { analytical: 2, problem_solving: 1, hands_on: 1, creative: 0, social: -1 }
          ),
          createChoice(
            'c3',
            'Ship with monitoring alerts and optimize if the impact is worse than expected',
            'Data-driven. Smart risk management.',
            { analytical: 2, problem_solving: 2, creative: 1, hands_on: 1, social: 0 }
          ),
        ]
      ),
      createStep(
        6,
        'Your feature ships successfully! The team celebrates, but you notice a few users already finding small UX issues.',
        'What\'s your next move?',
        [
          createChoice(
            'c1',
            'Take it as a learning moment and start planning improvements for v2',
            'Healthy mindset. Good growth opportunity.',
            { analytical: 2, problem_solving: 1, creative: 1, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Quickly patch everything without a review process',
            'Hasty. Might introduce new bugs.',
            { hands_on: 1, problem_solving: -1, analytical: -1, creative: 0, social: 0 }
          ),
          createChoice(
            'c3',
            'Present findings to the team and prioritize fixes based on impact',
            'Professional and collaborative.',
            { analytical: 2, social: 2, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
    ],
    minMasteryScore: 75,
    estimatedTime: 10,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 10,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// L3: Leading a Technical Initiative
const softwareEngineer_L3: QuizTemplate = {
  id: '',
  field_id: 'software-engineer',
  level: 3,
  title: 'Leading a Technical Initiative',
  description: 'You\'ve grown into a mid-level engineer. Now you\'re asked to lead a cross-team initiative to refactor a critical system.',
  difficulty_level: 'intermediate',
  quiz_data: {
    steps: [
      createStep(
        1,
        'Your manager asks you to lead a refactor of the payment system. It\'s currently working but brittle. Two other engineers will help.',
        'How do you kick off the project?',
        [
          createChoice(
            'c1',
            'Dive into the code and start refactoring immediately',
            'Energetic but lacks planning. Team gets confused.',
            { hands_on: 2, analytical: -1, problem_solving: -1, creative: 0, social: -1 }
          ),
          createChoice(
            'c2',
            'Schedule a meeting to discuss the problem, gather input, and create a plan',
            'Collaborative and thorough. Sets team up for success.',
            { analytical: 2, social: 2, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Write a design doc by yourself and present it to the team for feedback',
            'Good approach, though could be more collaborative upfront.',
            { analytical: 2, problem_solving: 1, creative: 1, hands_on: 0, social: 0 }
          ),
        ]
      ),
      createStep(
        2,
        'During planning, one engineer suggests a radically different architecture than what you were thinking. It\'s smart but risky.',
        'How do you handle it?',
        [
          createChoice(
            'c1',
            'Shut down the idea and stick with your plan (you\'re the lead)',
            'Authoritarian. Misses better ideas.',
            { social: -2, analytical: -1, problem_solving: -1, creative: -1, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Spend time exploring the new approach alongside your original idea',
            'Open-minded. Good technical leadership.',
            { analytical: 2, problem_solving: 2, creative: 1, social: 1, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Go with their idea immediately to show you\'re collaborative',
            'Too deferential. Lacks conviction.',
            { social: 1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        3,
        'Midway through, the project is taking longer than expected. Stakeholders are getting impatient. You could cut corners or ask for an extension.',
        'What do you do?',
        [
          createChoice(
            'c1',
            'Cut corners to meet the deadline',
            'Risky. Technical debt will haunt you.',
            { problem_solving: -1, analytical: -1, creative: 0, hands_on: 1, social: 0 }
          ),
          createChoice(
            'c2',
            'Ask for an extension without explaining why',
            'Vague. Doesn\'t address stakeholder concerns.',
            { social: -1, analytical: 0, problem_solving: 0, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Present a clear analysis of what\'s left, the risks of rushing, and a realistic timeline',
            'Transparent leadership. Builds trust.',
            { analytical: 2, social: 2, problem_solving: 2, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        4,
        'One of your team members is struggling and producing lower-quality work. You suspect they\'re overwhelmed.',
        'How do you address it?',
        [
          createChoice(
            'c1',
            'Pull them aside privately and ask how they\'re doing',
            'Empathetic and professional.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Publicly critique their work to motivate them',
            'Counterproductive. Demoralizes the team.',
            { social: -2, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Reassign their tasks to someone else without saying anything',
            'Avoids conflict but doesn\'t solve the problem.',
            { social: -1, analytical: -1, problem_solving: 0, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        5,
        'Your refactor deployment to production introduces a subtle bug that takes down the payment system for 20 minutes.',
        'How do you respond?',
        [
          createChoice(
            'c1',
            'Immediately own the mistake publicly and focus on fixing it',
            'Takes accountability. Builds trust despite the failure.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 1 }
          ),
          createChoice(
            'c2',
            'Blame the old system\'s complexity for the bug',
            'Deflects. Damages team trust.',
            { social: -2, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Quietly fix it and hope no one notices the incident happened',
            'Not transparent. Risky if discovered later.',
            { social: -1, analytical: -1, problem_solving: 0, creative: -1, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        6,
        'The refactor completes successfully. Your manager asks what you learned and what you\'d do differently next time.',
        'What do you say?',
        [
          createChoice(
            'c1',
            'Downplay the challenges and say it went smoothly',
            'Misses learning opportunity.',
            { analytical: -1, problem_solving: -1, creative: 0, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Reflect on what went well and what didn\'t, with specific ideas for improvement',
            'Excellent. Shows growth mindset and self-awareness.',
            { analytical: 2, problem_solving: 2, creative: 1, social: 1, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Focus only on the challenges and what went wrong',
            'One-sided. Doesn\'t acknowledge wins.',
            { analytical: 1, problem_solving: 1, creative: -1, social: -1, hands_on: 0 }
          ),
        ]
      ),
    ],
    minMasteryScore: 75,
    estimatedTime: 11,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 11,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// L4: System Architecture Decision
const softwareEngineer_L4: QuizTemplate = {
  id: '',
  field_id: 'software-engineer',
  level: 4,
  title: 'System Architecture Decision',
  description: 'You\'re now a senior engineer. You\'re designing a new microservices architecture for the platform.',
  difficulty_level: 'advanced',
  quiz_data: {
    steps: [
      createStep(
        1,
        'Your company is scaling. You\'re architecting a move from monolith to microservices. The timeline is tight, but quality matters.',
        'How do you approach this decision?',
        [
          createChoice(
            'c1',
            'Follow the latest microservices trends (the cool choice)',
            'Risks over-engineering and complexity.',
            { creative: 1, analytical: -1, problem_solving: -1, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Analyze your current pain points and design based on actual needs',
            'Pragmatic and data-driven.',
            { analytical: 2, problem_solving: 2, creative: 0, hands_on: 1, social: 0 }
          ),
          createChoice(
            'c3',
            'Propose a hybrid approach with a phased rollout',
            'Balanced. Reduces risk.',
            { analytical: 2, problem_solving: 2, creative: 1, hands_on: 1, social: 0 }
          ),
        ]
      ),
      createStep(
        2,
        'During design review, a younger engineer challenges your architecture, saying it\'s too conservative and won\'t scale.',
        'How do you respond?',
        [
          createChoice(
            'c1',
            'Dismiss their concern—you have more experience',
            'Closed-minded. Misses potential insights.',
            { social: -2, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Engage with their ideas seriously and explain your reasoning for the conservative approach',
            'Leadership. Shows you value input and can explain tradeoffs.',
            { analytical: 2, social: 2, problem_solving: 1, creative: 1, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Adopt their approach to show you\'re modern and collaborative',
            'Too deferential. Abandons your analysis.',
            { social: 1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        3,
        'You realize the architecture has a critical flaw that could cause data consistency issues. You\'re already deep in implementation with the team.',
        'What do you do?',
        [
          createChoice(
            'c1',
            'Continue and hope it doesn\'t become a real issue',
            'Dangerous. Puts company at risk.',
            { analytical: -2, problem_solving: -2, creative: 0, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Stop everything and redesign from scratch',
            'Thorough but wasteful if it can be patched.',
            { analytical: 1, problem_solving: -1, creative: 0, hands_on: 1, social: -1 }
          ),
          createChoice(
            'c3',
            'Propose a specific mitigation strategy and get stakeholder alignment before proceeding',
            'Honest and responsible.',
            { analytical: 2, problem_solving: 2, social: 2, creative: 0, hands_on: 1 }
          ),
        ]
      ),
      createStep(
        4,
        'You need to communicate this architecture to executive leadership. They care about timeline and cost, not technical details.',
        'How do you present it?',
        [
          createChoice(
            'c1',
            'Dive deep into the technical details and why microservices matter',
            'Wrong audience. They\'ll tune out.',
            { analytical: 2, problem_solving: -1, creative: -1, hands_on: 0, social: -1 }
          ),
          createChoice(
            'c2',
            'Focus on business outcomes: faster time-to-market, reduced operational costs, ability to scale',
            'Perfect. Speaks their language.',
            { analytical: 2, social: 2, problem_solving: 1, creative: 1, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Give a high-level overview without diving into complexity or risks',
            'Too vague. Misses important context.',
            { social: 1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        5,
        'Implementation reveals a dependency on an external service that\'s not as reliable as you assumed. You could rearchitect or build redundancy.',
        'What\'s your call?',
        [
          createChoice(
            'c1',
            'Rearchitect to remove the dependency',
            'Comprehensive but time-consuming.',
            { analytical: 2, problem_solving: 1, hands_on: 2, creative: 1, social: -1 }
          ),
          createChoice(
            'c2',
            'Build redundancy and failover mechanisms',
            'Pragmatic. Solves the immediate problem.',
            { analytical: 2, problem_solving: 2, hands_on: 1, creative: 0, social: 0 }
          ),
          createChoice(
            'c3',
            'Accept the risk and monitor closely',
            'Risky if the service fails.',
            { analytical: 0, problem_solving: -1, hands_on: 0, creative: -1, social: 0 }
          ),
        ]
      ),
      createStep(
        6,
        'The architecture is complete. You\'ve mentored three junior engineers through the process. One asks for advice on advancing their career.',
        'What do you share?',
        [
          createChoice(
            'c1',
            'Tell them to work on whatever they\'re most interested in',
            'Too vague. Doesn\'t help their growth.',
            { social: 0, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Help them identify skill gaps and create a plan to address them',
            'Great mentorship. Shows investment in their growth.',
            { social: 2, analytical: 2, problem_solving: 1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Tell them to focus only on coding and not worry about leadership',
            'Limiting. Not everyone wants the same path.',
            { social: -1, analytical: 0, problem_solving: -1, creative: -1, hands_on: 0 }
          ),
        ]
      ),
    ],
    minMasteryScore: 75,
    estimatedTime: 12,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 12,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// L5: Tech Strategy for Your Team
const softwareEngineer_L5: QuizTemplate = {
  id: '',
  field_id: 'software-engineer',
  level: 5,
  title: 'Tech Strategy for Your Team',
  description: 'You\'re leading a team of 8 engineers. You\'re setting the technical strategy for the next year.',
  difficulty_level: 'expert',
  quiz_data: {
    steps: [
      createStep(
        1,
        'The company wants to adopt AI/ML for recommendations. Your team has limited ML expertise. You could hire specialists, train existing staff, or partner with another team.',
        'How do you navigate this?',
        [
          createChoice(
            'c1',
            'Hire ML specialists to handle it independently',
            'Brings expertise but siloes knowledge.',
            { analytical: 1, social: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Invest time in training your team on ML fundamentals',
            'Slow but builds capability.',
            { social: 2, analytical: 1, problem_solving: 1, creative: 1, hands_on: 1 }
          ),
          createChoice(
            'c3',
            'Combine both: hire one specialist and pair them with your team for knowledge transfer',
            'Balanced. Best long-term outcome.',
            { analytical: 2, social: 2, problem_solving: 2, creative: 1, hands_on: 1 }
          ),
        ]
      ),
      createStep(
        2,
        'Your team is split on tech stack choices. Some want to stick with proven tech; others push for newer frameworks. Friction is rising.',
        'How do you resolve this?',
        [
          createChoice(
            'c1',
            'Make the call yourself based on what you think is best',
            'Authoritarian. Ignores team input.',
            { social: -1, analytical: 0, problem_solving: 0, creative: -1, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Facilitate a discussion where the team presents evidence for each option',
            'Democratic and data-driven. Great leadership.',
            { analytical: 2, social: 2, problem_solving: 2, creative: 1, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Compromise by splitting the team into different projects using different stacks',
            'Addresses both sides but creates complexity.',
            { social: 1, analytical: 1, problem_solving: 1, creative: 1, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        3,
        'A critical system is failing due to tech debt accumulated over years. Fixing it requires 2 engineers full-time for 2 months, but you\'re also delivering a new feature.',
        'What\'s your strategy?',
        [
          createChoice(
            'c1',
            'Put tech debt on hold and focus on the feature',
            'Short-term gain, long-term pain.',
            { problem_solving: -1, analytical: -1, creative: 0, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Stop everything and fix the tech debt',
            'Responsible but could disappoint product stakeholders.',
            { analytical: 1, problem_solving: 1, creative: -1, hands_on: 1, social: -1 }
          ),
          createChoice(
            'c3',
            'Negotiate with product to phase the feature while allocating resources to tech debt',
            'Strategic. Balances long-term health with delivery.',
            { analytical: 2, social: 2, problem_solving: 2, creative: 1, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        4,
        'You discover that one engineer is regularly shipping code without proper testing. They\'re fast but risky.',
        'How do you handle this?',
        [
          createChoice(
            'c1',
            'Publicly call them out in a team meeting',
            'Humiliating. Damages team culture.',
            { social: -2, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Have a private conversation to understand why and agree on standards',
            'Respectful and effective.',
            { social: 2, analytical: 1, problem_solving: 2, creative: 0, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Implement stricter code review process for everyone',
            'Treats the symptom, not the cause.',
            { analytical: 1, problem_solving: -1, creative: 0, hands_on: 1, social: -1 }
          ),
        ]
      ),
      createStep(
        5,
        'You\'re asked to present your tech strategy to the board. You have 15 minutes. They asked "how is our tech helping us win?"',
        'How do you frame it?',
        [
          createChoice(
            'c1',
            'Focus on the technologies themselves (Kubernetes, microservices, etc.)',
            'Wrong approach. Board cares about impact.',
            { analytical: 1, social: -1, problem_solving: -1, creative: -1, hands_on: 0 }
          ),
          createChoice(
            'c2',
            'Connect tech decisions to business outcomes: faster feature velocity, reduced operational costs, better reliability',
            'Perfect. Shows strategic thinking.',
            { analytical: 2, social: 2, problem_solving: 2, creative: 1, hands_on: 0 }
          ),
          createChoice(
            'c3',
            'Ask them what they think our tech strategy should be',
            'Defers instead of leading.',
            { social: 1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }
          ),
        ]
      ),
      createStep(
        6,
        'Looking ahead to next year, you realize your team might be outpaced by competitors using new technologies.',
        'How do you stay ahead?',
        [
          createChoice(
            'c1',
            'Chase every new technology trend',
            'Risky and exhausting. Distracts from core work.',
            { creative: 2, analytical: -2, problem_solving: -1, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c2',
            'Stick with what\'s proven and ignore trends',
            'Safe but risks falling behind.',
            { analytical: 1, problem_solving: -1, creative: -1, hands_on: 0, social: 0 }
          ),
          createChoice(
            'c3',
            'Monitor emerging trends, evaluate fit strategically, and dedicate time to experimentation',
            'Balanced innovation approach.',
            { analytical: 2, problem_solving: 2, creative: 2, hands_on: 1, social: 0 }
          ),
        ]
      ),
    ],
    minMasteryScore: 75,
    estimatedTime: 13,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 13,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// FIELD 2: NURSE
const nurse_L1: QuizTemplate = {
  id: '',
  field_id: 'nurse',
  level: 1,
  title: 'Your First Shift in the Hospital',
  description: 'You just graduated from nursing school and start your first shift at a busy hospital.',
  difficulty_level: 'basic',
  quiz_data: {
    steps: [
      createStep(1, 'Before your shift, your preceptor asks if you want to observe or jump in immediately.', 'What do you choose?', [
        createChoice('c1', 'Observe first to get oriented', 'Smart—builds confidence.', { analytical: 2, hands_on: 0, social: 0, creative: 0, problem_solving: 0 }),
        createChoice('c2', 'Jump in with your preceptor by your side', 'Brave and efficient.', { hands_on: 2, analytical: 1, social: 0, creative: 0, problem_solving: 0 }),
        createChoice('c3', 'Ask your preceptor what they recommend', 'Shows good judgment seeking guidance.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
      ]),
      createStep(2, 'A patient is in pain but their pain medication isn\'t due for another 30 minutes. They ask you to give it early.', 'How do you handle this?', [
        createChoice('c1', 'Give it early to help them', 'Caring but violates protocol.', { social: 2, hands_on: -1, analytical: -1, problem_solving: -1, creative: 0 }),
        createChoice('c2', 'Explain the schedule and stick to it', 'Professional but maybe dismissive.', { analytical: 1, hands_on: 0, social: -1, creative: 0, problem_solving: 0 }),
        createChoice('c3', 'Ask your preceptor or the doctor about options', 'Responsible—follows proper channels.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
      ]),
      createStep(3, 'You notice a patient\'s vital signs are slightly off from earlier. The reading might be a mistake.', 'What do you do?', [
        createChoice('c1', 'Assume it\'s an error and move on', 'Risky—could miss something.', { analytical: -1, hands_on: -1, problem_solving: -1, social: 0, creative: 0 }),
        createChoice('c2', 'Recheck the vitals and report any concerns', 'Thorough and safe.', { analytical: 2, hands_on: 1, problem_solving: 1, social: 0, creative: 0 }),
        createChoice('c3', 'Tell your preceptor immediately without rechecking', 'Cautious but might create alarm over nothing.', { social: 1, analytical: 0, problem_solving: 0, creative: 0, hands_on: -1 }),
      ]),
      createStep(4, 'During rounds, the doctor asks you for updates on your patients. You\'re nervous about speaking up.', 'How do you respond?', [
        createChoice('c1', 'Stay quiet and let more experienced nurses talk', 'Misses opportunity to demonstrate knowledge.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Share what you observed, focusing on facts', 'Perfect—professional communication.', { analytical: 2, social: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Give a long, detailed story about each patient', 'Too verbose—people want efficiency.', { analytical: 0, social: 0, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
      createStep(5, 'A family member is upset about their loved one\'s care. They\'re speaking loudly in the hallway.', 'What\'s your approach?', [
        createChoice('c1', 'Listen to their concerns and stay calm', 'De-escalates the situation.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Defend yourself and the care provided', 'Defensive. Escalates tension.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Get your supervisor involved immediately', 'Good instinct but could handle initial conversation first.', { social: 0, analytical: 1, problem_solving: 0, creative: 0, hands_on: 0 }),
      ]),
      createStep(6, 'End of shift. You\'re exhausted but also energized. A colleague asks how it went.', 'How do you reflect?', [
        createChoice('c1', 'Say it was fine and head home', 'Misses team connection.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Share what you learned and ask for feedback', 'Great growth mindset.', { social: 2, analytical: 2, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Vent about everything that was hard', 'Honest but might drain your support system.', { social: 0, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 8,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 8,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const nurse_L2: QuizTemplate = {
  id: '',
  field_id: 'nurse',
  level: 2,
  title: 'Managing a Complex Patient',
  description: 'After 6 months, you\'re handling more complex patient cases with less supervision.',
  difficulty_level: 'intermediate',
  quiz_data: {
    steps: [
      createStep(1, 'You\'re assigned a patient with multiple conditions and complicated medication interactions. The chart is dense.', 'How do you approach it?', [
        createChoice('c1', 'Dive in and start administering care', 'Risky—might miss important info.', { hands_on: 1, analytical: -1, problem_solving: -1, social: 0, creative: 0 }),
        createChoice('c2', 'Take time to thoroughly understand the patient history and medications', 'Thorough and safe.', { analytical: 2, hands_on: 1, problem_solving: 1, social: 0, creative: 0 }),
        createChoice('c3', 'Ask your supervisor to walk you through it', 'Good support-seeking, though you could try first.', { social: 2, analytical: 0, problem_solving: 0, creative: 0, hands_on: 0 }),
      ]),
      createStep(2, 'The patient reports symptoms that don\'t match their diagnosis. You suspect it might be a medication side effect.', 'What do you do?', [
        createChoice('c1', 'Document it but don\'t mention it to the doctor', 'Passive—misses treatment opportunity.', { analytical: -1, hands_on: 0, problem_solving: -1, social: -1, creative: 0 }),
        createChoice('c2', 'Present your observations to the doctor with your hypothesis', 'Excellent clinical reasoning.', { analytical: 2, social: 1, problem_solving: 2, creative: 1, hands_on: 0 }),
        createChoice('c3', 'Tell the patient to report it to the doctor themselves', 'Passes responsibility instead of advocating.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
      createStep(3, 'A nurse colleague suggests an alternative treatment that might be faster but isn\'t standard protocol.', 'How do you respond?', [
        createChoice('c1', 'Try it—nurses know what works', 'Risky without proper authorization.', { hands_on: 1, analytical: -1, problem_solving: -1, social: 0, creative: 1 }),
        createChoice('c2', 'Suggest following established protocols to ensure consistency', 'Safe, though maybe dismissive of experience.', { analytical: 1, hands_on: 0, problem_solving: 1, social: -1, creative: 0 }),
        createChoice('c3', 'Discuss with your supervisor and research the evidence', 'Balanced—respects input while maintaining safety.', { analytical: 2, social: 1, problem_solving: 1, creative: 0, hands_on: 1 }),
      ]),
      createStep(4, 'You\'re overwhelmed with your patient load and falling behind schedule. A colleague offers to help with one patient.', 'How do you respond?', [
        createChoice('c1', 'Accept immediately—teamwork matters', 'Good, but take ownership of your work.', { social: 2, analytical: 0, problem_solving: 0, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Decline and push through', 'Independent but unsustainable.', { analytical: -1, hands_on: 2, problem_solving: -1, social: -1, creative: 0 }),
        createChoice('c3', 'Accept help but make sure you stay involved in continuity of care', 'Professional and collaborative.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 1 }),
      ]),
      createStep(5, 'A patient is noncompliant with treatment and it\'s affecting their recovery. They seem resistant.', 'What\'s your approach?', [
        createChoice('c1', 'Be firm and tell them they need to follow the plan', 'Authoritarian. Damages rapport.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Ask questions to understand their concerns', 'Patient-centered. Effective.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Document non-compliance and move on', 'Passive—misses opportunity to help.', { analytical: 0, hands_on: -1, problem_solving: -1, social: -1, creative: 0 }),
      ]),
      createStep(6, 'You make a minor medication administration error that didn\'t harm the patient.', 'How do you handle it?', [
        createChoice('c1', 'Say nothing since no harm was done', 'Risky. Undermines trust if discovered.', { social: -1, analytical: -1, problem_solving: -1, creative: -1, hands_on: 0 }),
        createChoice('c2', 'Report it immediately to your supervisor', 'Transparent and responsible.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Tell the patient but not management', 'Partial transparency—incomplete.', { social: 1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 10,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 10,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// Continuing with L3, L4, L5 for Nurse - condensed format
const nurse_L3: QuizTemplate = {
  id: '',
  field_id: 'nurse',
  level: 3,
  title: 'Mentoring New Nurses',
  description: 'You\'re now a charge nurse mentoring new staff.',
  difficulty_level: 'intermediate',
  quiz_data: {
    steps: [
      createStep(1, 'A new nurse makes a mistake in patient care. It didn\'t cause harm. How do you address it?', 'Your approach:', [
        createChoice('c1', 'Publicly correct them so others learn', 'Humiliating and ineffective.', { social: -2, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Speak privately and focus on the learning opportunity', 'Great mentorship.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Let it slide—they\'ll figure it out', 'Misses teaching moment.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
      createStep(2, 'Two nurses disagree about how to handle a patient situation. They ask you to settle it.', 'How do you handle conflict?', [
        createChoice('c1', 'Impose your decision as the charge nurse', 'Authoritarian. Misses inputs.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Facilitate discussion and find common ground', 'Excellent leadership.', { social: 2, analytical: 1, problem_solving: 2, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Tell them to work it out themselves', 'Abdicates responsibility.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
      createStep(3, 'You notice the unit is understaffed and quality of care is slipping. Management hasn\'t responded to your concerns.', 'Next step?', [
        createChoice('c1', 'Keep pushing in formal channels', 'Appropriate but persistent.', { social: 1, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Accept it and do your best', 'Passive. Patient safety at risk.', { analytical: -1, hands_on: 1, problem_solving: -1, social: 0, creative: 0 }),
        createChoice('c3', 'Document concerns and escalate to patient safety committee', 'Professional advocacy.', { analytical: 2, social: 1, problem_solving: 2, creative: 0, hands_on: 1 }),
      ]),
      createStep(4, 'A patient asks for advice about a medical decision you\'re not qualified to give.', 'How do you respond?', [
        createChoice('c1', 'Share your opinion on what\'s best', 'Overstepping—not your role.', { analytical: -1, social: 1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Suggest they ask their doctor', 'Appropriate boundary.', { social: 1, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Provide information but let them decide', 'Balanced patient advocacy.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
      ]),
      createStep(5, 'You\'re interested in pursuing advanced nursing certification.', 'How do you balance it with your current role?', [
        createChoice('c1', 'Put it off until things are less busy', 'Procrastination. Might never happen.', { analytical: -1, hands_on: 0, problem_solving: -1, social: 0, creative: 0 }),
        createChoice('c2', 'Pursue it aggressively even if it affects your current work', 'Self-focused.', { analytical: 0, hands_on: 1, problem_solving: -1, social: -1, creative: 0 }),
        createChoice('c3', 'Create a realistic plan that doesn\'t compromise current patients', 'Mature growth planning.', { analytical: 2, social: 1, problem_solving: 2, creative: 0, hands_on: 1 }),
      ]),
      createStep(6, 'A colleague is struggling with burnout and considering leaving.', 'They ask for advice.', [
        createChoice('c1', 'Tell them to leave if they\'re unhappy', 'Dismissive of their struggle.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Listen deeply and help them explore options', 'Great mentorship and support.', { social: 2, analytical: 2, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Tell them it gets easier but give no practical help', 'Vague reassurance.', { social: 0, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 11,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 11,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const nurse_L4: QuizTemplate = {
  id: '',
  field_id: 'nurse',
  level: 4,
  title: 'Leading Nursing Innovation',
  description: 'You\'re leading a project to improve patient outcomes in your unit.',
  difficulty_level: 'advanced',
  quiz_data: {
    steps: [
      createStep(1, 'You\'ve identified a process that could improve patient safety. Implementation requires staff training and protocol changes.', 'How do you approach change management?', [
        createChoice('c1', 'Mandate the change immediately', 'Resistance likely.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Involve staff from the beginning in designing the solution', 'Excellent. Builds buy-in.', { social: 2, analytical: 2, problem_solving: 2, creative: 1, hands_on: 0 }),
        createChoice('c3', 'Pilot it with a small group first', 'Good, but should involve staff earlier.', { analytical: 1, hands_on: 1, problem_solving: 1, social: 1, creative: 0 }),
      ]),
      createStep(2, 'Data shows your unit has better patient outcomes than hospitals nationally. Leadership wants to share your model.', 'How do you balance pride and humility?', [
        createChoice('c1', 'Claim credit for the success', 'Arrogant. Ignores team effort.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Emphasize it\'s a team achievement and share learnings openly', 'Generous leadership.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Downplay it and say it\'s just luck', 'False humility. Misses opportunity.', { analytical: -1, social: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
      createStep(3, 'A new treatment protocol shows promise but lacks full evidence. Adopting it could help some patients but might harm others.', 'How do you decide?', [
        createChoice('c1', 'Adopt it enthusiastically—innovation is good', 'Reckless. Patient safety risk.', { hands_on: 1, problem_solving: -2, analytical: -1, creative: 1, social: 0 }),
        createChoice('c2', 'Reject it until full evidence is available', 'Conservative but might delay help.', { analytical: 1, problem_solving: -1, creative: -1, hands_on: 0, social: 0 }),
        createChoice('c3', 'Design a controlled study to gather evidence safely', 'Rigorous and ethical.', { analytical: 2, problem_solving: 2, creative: 1, hands_on: 1, social: 0 }),
      ]),
      createStep(4, 'You\'re being considered for a director role but it means less direct patient care.', 'How do you decide?', [
        createChoice('c1', 'Take it for the status and pay increase', 'Self-focused. You might not excel.', { analytical: -1, social: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Decline to stay close to patients', 'Undervalues your leadership impact.', { analytical: 0, hands_on: 1, problem_solving: 0, social: -1, creative: 0 }),
        createChoice('c3', 'Explore the role carefully and consider your impact potential', 'Thoughtful career decision.', { analytical: 2, problem_solving: 1, social: 1, creative: 0, hands_on: 0 }),
      ]),
      createStep(5, 'You discover systemic issues in patient care that require addressing hospital-wide policies. It\'s politically risky.', 'What do you do?', [
        createChoice('c1', 'Stay quiet to protect your position', 'Cowardly. Patients suffer.', { social: -2, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Present findings through appropriate channels with evidence', 'Courageous and professional.', { analytical: 2, social: 1, problem_solving: 2, creative: 0, hands_on: 1 }),
        createChoice('c3', 'Bypass formal channels and go public', 'Risky. Could backfire.', { analytical: 0, social: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
      createStep(6, 'Your legacy in nursing is developing strong leaders.', 'How do you prioritize this?', [
        createChoice('c1', 'Focus on your own advancement', 'Misses lasting impact.', { analytical: -1, social: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Dedicate time to mentoring and developing others', 'Transformational leadership.', { social: 2, analytical: 1, problem_solving: 1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Let younger nurses figure it out themselves', 'Misses opportunity.', { social: -1, analytical: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 12,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 12,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const nurse_L5: QuizTemplate = {
  id: '',
  field_id: 'nurse',
  level: 5,
  title: 'Healthcare System Leadership',
  description: 'You\'re now influencing nursing practice and policy at a health system level.',
  difficulty_level: 'expert',
  quiz_data: {
    steps: [
      createStep(1, 'Your health system faces a nursing shortage. Solutions range from raises to recruitment to process changes.', 'How do you approach systemic problem-solving?', [
        createChoice('c1', 'Focus solely on hiring more nurses', 'Treats symptom, not cause.', { analytical: -1, problem_solving: -1, creative: -1, social: 0, hands_on: 1 }),
        createChoice('c2', 'Analyze root causes and propose multi-faceted solutions', 'Strategic and comprehensive.', { analytical: 2, problem_solving: 2, creative: 1, social: 1, hands_on: 0 }),
        createChoice('c3', 'Accept it as inevitable and manage with what you have', 'Defeatist. Misses opportunity.', { analytical: -1, problem_solving: -1, creative: -1, social: 0, hands_on: 0 }),
      ]),
      createStep(2, 'You\'re designing nursing curriculum for the region.', 'What priorities do you set?', [
        createChoice('c1', 'Focus on technical skills only', 'Incomplete. Ignores leadership.', { analytical: 0, hands_on: 2, problem_solving: -1, social: -1, creative: 0 }),
        createChoice('c2', 'Balance clinical excellence with leadership, ethics, and innovation', 'Holistic nursing education.', { analytical: 2, social: 2, problem_solving: 2, creative: 1, hands_on: 1 }),
        createChoice('c3', 'Emphasize whatever your hospital needs right now', 'Too reactive. Lacks vision.', { analytical: 0, problem_solving: 0, creative: -1, social: 0, hands_on: 1 }),
      ]),
      createStep(3, 'There\'s political pressure to cut nursing hours to reduce costs. You have data showing it harms outcomes.', 'What do you do?', [
        createChoice('c1', 'Give up and accept budget cuts', 'Surrender. Patients suffer.', { analytical: -1, problem_solving: -1, social: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Present strong evidence to leadership and propose alternatives', 'Courageous advocacy backed by data.', { analytical: 2, social: 2, problem_solving: 2, creative: 1, hands_on: 0 }),
        createChoice('c3', 'Work quietly to minimize harm without challenging leadership', 'Doesn\'t address root issue.', { analytical: -1, problem_solving: 0, social: -1, creative: 0, hands_on: 1 }),
      ]),
      createStep(4, 'You have opportunity to shape national nursing policy.', 'What\'s your vision?', [
        createChoice('c1', 'Maintain current practices—if it\'s not broken, don\'t fix it', 'No vision for progress.', { analytical: -1, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
        createChoice('c2', 'Propose transformative changes based on evidence and patient outcomes', 'Visionary leadership.', { analytical: 2, creative: 2, problem_solving: 2, social: 1, hands_on: 0 }),
        createChoice('c3', 'Follow what other countries are doing', 'Derivative. Lacks independent thinking.', { analytical: 0, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
      ]),
      createStep(5, 'You\'re asked to balance equity in healthcare access with financial sustainability.', 'How do you proceed?', [
        createChoice('c1', 'Prioritize access regardless of cost', 'Idealistic but unsustainable.', { social: 1, problem_solving: -1, analytical: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Prioritize financial health even if it limits access', 'Cold. Misses mission.', { analytical: 1, social: -2, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c3', 'Develop solutions that advance both equity and sustainability', 'Strategic problem-solving.', { analytical: 2, social: 2, problem_solving: 2, creative: 2, hands_on: 0 }),
      ]),
      createStep(6, 'Reflecting on your career.', 'What impact do you want nursing to have?', [
        createChoice('c1', 'Personal success and recognition', 'Self-focused. Limited legacy.', { analytical: -1, social: -1, problem_solving: -1, creative: 0, hands_on: 0 }),
        createChoice('c2', 'Transform nursing to be seen as central to healthcare excellence and equity', 'Transformational vision.', { analytical: 2, creative: 2, problem_solving: 2, social: 2, hands_on: 0 }),
        createChoice('c3', 'Maintain the status quo and pass leadership to younger generation', 'Safe but uninspiring.', { analytical: 0, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 13,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 13,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// FIELD 5: ARCHITECT
const architect_L1: QuizTemplate = {
  id: '',
  field_id: 'architect',
  level: 1,
  title: 'Your First Project as an Architect',
  description: 'You\'re starting your career in architecture. Navigate your first major design project.',
  difficulty_level: 'basic',
  quiz_data: {
    steps: [
      createStep(1, 'You\'re assigned your first project: a 5-story office building downtown.', 'What\'s your initial approach?', [
        createChoice('c1', 'Follow the standard office design without innovation', 'Safe but uninspired.', { analytical: 1, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
        createChoice('c2', 'Propose a sustainable design with green spaces and natural light', 'Thoughtful and forward-thinking.', { analytical: 2, creative: 2, problem_solving: 1, social: 1, hands_on: 0 }),
        createChoice('c3', 'Design something bold and experimental to make your mark', 'Ambitious but risky for first project.', { analytical: 0, creative: 2, problem_solving: 1, social: -1, hands_on: 1 }),
      ]),
      createStep(2, 'The client wants to cut costs significantly.', 'How do you respond?', [
        createChoice('c1', 'Accept and redesign with cheaper materials', 'Compromises quality.', { analytical: 1, creative: -1, problem_solving: 0, social: 1, hands_on: 1 }),
        createChoice('c2', 'Show data on long-term value of better design and materials', 'Educates client while maintaining standards.', { analytical: 2, creative: 0, problem_solving: 2, social: 1, hands_on: 0 }),
        createChoice('c3', 'Propose phased construction to deliver within budget', 'Pragmatic solution.', { analytical: 2, creative: 1, problem_solving: 2, social: 1, hands_on: 1 }),
      ]),
      createStep(3, 'A structural engineer challenges your design, saying it\'s over-engineered.', 'What do you do?', [
        createChoice('c1', 'Defend your design passionately without compromise', 'Inflexible approach.', { analytical: 0, creative: -1, problem_solving: -1, social: -1, hands_on: 0 }),
        createChoice('c2', 'Collaborate with the engineer to find optimal balance', 'Professional and collaborative.', { analytical: 2, creative: 1, problem_solving: 2, social: 2, hands_on: 1 }),
        createChoice('c3', 'Trust their expertise and simplify the design', 'Defers too easily.', { analytical: 1, creative: -1, problem_solving: 0, social: 1, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 10,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 10,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const architect_L2: QuizTemplate = {
  id: '',
  field_id: 'architect',
  level: 2,
  title: 'Leading a Complex Urban Project',
  description: 'You\'re lead architect on a mixed-use development in a historic district.',
  difficulty_level: 'intermediate',
  quiz_data: {
    steps: [
      createStep(1, 'The project sits in a historic district with strict preservation rules.', 'How do you approach this constraint?', [
        createChoice('c1', 'Strictly follow historic guidelines without innovation', 'Misses opportunity for integration.', { analytical: 1, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
        createChoice('c2', 'Design something that respects history while adding modern elements thoughtfully', 'Balanced and innovative.', { analytical: 2, creative: 2, problem_solving: 2, social: 1, hands_on: 0 }),
        createChoice('c3', 'Push the rules to create something bold and contemporary', 'Risky politically.', { analytical: 0, creative: 2, problem_solving: 1, social: -1, hands_on: 1 }),
      ]),
      createStep(2, 'Community groups have conflicting concerns about the project.', 'How do you manage stakeholders?', [
        createChoice('c1', 'Ignore objections and proceed with your vision', 'Arrogant and risky.', { analytical: -1, creative: -1, problem_solving: -1, social: -2, hands_on: 0 }),
        createChoice('c2', 'Hold listening sessions and integrate community feedback', 'Democratic and collaborative.', { analytical: 1, creative: 1, problem_solving: 2, social: 2, hands_on: 0 }),
        createChoice('c3', 'Present a single proposal and let them accept or reject', 'Inflexible.', { analytical: 1, creative: 0, problem_solving: 0, social: -1, hands_on: 0 }),
      ]),
      createStep(3, 'Budget increases are needed for your revised design.', 'What\'s your strategy?', [
        createChoice('c1', 'Cut corners to stay within budget', 'Compromises vision.', { analytical: -1, creative: -1, problem_solving: -1, social: 0, hands_on: 1 }),
        createChoice('c2', 'Present detailed ROI analysis showing value of enhanced design', 'Strategic and data-driven.', { analytical: 2, creative: 0, problem_solving: 2, social: 1, hands_on: 0 }),
        createChoice('c3', 'Redesign efficiently while maintaining quality', 'Problem-solving focused.', { analytical: 2, creative: 1, problem_solving: 2, social: 0, hands_on: 1 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 11,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 11,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const architect_L3: QuizTemplate = {
  id: '',
  field_id: 'architect',
  level: 3,
  title: 'Sustainable Design Leadership',
  description: 'You\'re designing a zero-carbon office campus with cutting-edge sustainability.',
  difficulty_level: 'intermediate',
  quiz_data: {
    steps: [
      createStep(1, 'The client wants sustainable design, but it costs 20% more upfront.', 'How do you justify it?', [
        createChoice('c1', 'Design conventionally to save costs', 'Misses opportunity.', { analytical: -1, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
        createChoice('c2', 'Show 30-year lifecycle costs and environmental benefits', 'Strategic thinking.', { analytical: 2, creative: 1, problem_solving: 2, social: 1, hands_on: 0 }),
        createChoice('c3', 'Design sustainable anyway and convince them after', 'Risky approach.', { analytical: 0, creative: 1, problem_solving: 1, social: -1, hands_on: 1 }),
      ]),
      createStep(2, 'Your innovative materials are untested at scale.', 'What do you do?', [
        createChoice('c1', 'Use proven materials to avoid risk', 'Conservative but limits innovation.', { analytical: 1, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
        createChoice('c2', 'Test thoroughly before full implementation', 'Methodical and smart.', { analytical: 2, creative: 1, problem_solving: 2, social: 0, hands_on: 2 }),
        createChoice('c3', 'Use them anyway—innovation requires risk', 'Bold but potentially reckless.', { analytical: 0, creative: 2, problem_solving: 1, social: -1, hands_on: 1 }),
      ]),
      createStep(3, 'A team member suggests a simpler approach that\'s less sustainable.', 'How do you lead?', [
        createChoice('c1', 'Override their suggestion and proceed with original plan', 'Authoritarian.', { analytical: 1, creative: 0, problem_solving: -1, social: -1, hands_on: 0 }),
        createChoice('c2', 'Listen to their concerns, explain tradeoffs, and collaborate on best approach', 'Collaborative leadership.', { analytical: 2, creative: 1, problem_solving: 2, social: 2, hands_on: 1 }),
        createChoice('c3', 'Accept their approach to keep team harmony', 'Avoids necessary decisions.', { analytical: -1, creative: -1, problem_solving: -1, social: 1, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 12,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 12,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const architect_L4: QuizTemplate = {
  id: '',
  field_id: 'architect',
  level: 4,
  title: 'Principal Architect: City-Scale Planning',
  description: 'You\'re now overseeing the master plan for an entire neighborhood development.',
  difficulty_level: 'advanced',
  quiz_data: {
    steps: [
      createStep(1, 'You\'re designing a neighborhood that must balance housing, commerce, and green space.', 'What\'s your vision?', [
        createChoice('c1', 'Maximize density and commercial revenue', 'Profitable but soulless.', { analytical: 1, creative: -1, problem_solving: 0, social: -1, hands_on: 0 }),
        createChoice('c2', 'Create a mixed-income, mixed-use neighborhood with ample green space', 'Visionary and inclusive.', { analytical: 2, creative: 2, problem_solving: 2, social: 2, hands_on: 1 }),
        createChoice('c3', 'Focus on aesthetic beauty over practical functionality', 'Pretty but impractical.', { analytical: -1, creative: 2, problem_solving: -1, social: 0, hands_on: 0 }),
      ]),
      createStep(2, 'Political pressure exists to reduce environmental standards for development speed.', 'How do you respond?', [
        createChoice('c1', 'Agree to reduce standards to move the project forward', 'Compromises integrity.', { analytical: -1, creative: -1, problem_solving: -1, social: 1, hands_on: 0 }),
        createChoice('c2', 'Present data showing sustainable design creates long-term value', 'Principled and strategic.', { analytical: 2, creative: 0, problem_solving: 2, social: 1, hands_on: 0 }),
        createChoice('c3', 'Stand firm against pressure regardless of consequences', 'Idealistic but risky.', { analytical: 1, creative: -1, problem_solving: -1, social: -1, hands_on: 0 }),
      ]),
      createStep(3, 'An emerging technology could revolutionize the project but requires learning new methods.', 'What\'s your approach?', [
        createChoice('c1', 'Stick with proven methods you know', 'Misses opportunity.', { analytical: 0, creative: -1, problem_solving: -1, social: 0, hands_on: -1 }),
        createChoice('c2', 'Investigate, pilot test, and integrate if valuable', 'Balanced innovation.', { analytical: 2, creative: 1, problem_solving: 2, social: 0, hands_on: 2 }),
        createChoice('c3', 'Adopt it fully immediately without proper vetting', 'Reckless.', { analytical: -1, creative: 2, problem_solving: -1, social: 0, hands_on: 1 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 13,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 13,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const architect_L5: QuizTemplate = {
  id: '',
  field_id: 'architect',
  level: 5,
  title: 'Visionary Architecture: Shaping the Future',
  description: 'You\'re a recognized thought leader designing a landmark that will influence architecture globally.',
  difficulty_level: 'advanced',
  quiz_data: {
    steps: [
      createStep(1, 'You have freedom to design something truly innovative and paradigm-shifting.', 'What\'s your legacy project?', [
        createChoice('c1', 'Play it safe with a refined but conventional design', 'Wasted opportunity.', { analytical: 0, creative: -1, problem_solving: -1, social: 0, hands_on: 0 }),
        createChoice('c2', 'Design something innovative that challenges conventions while remaining functional', 'True visionary leadership.', { analytical: 2, creative: 2, problem_solving: 2, social: 1, hands_on: 1 }),
        createChoice('c3', 'Create radical experimental architecture that ignores practical concerns', 'Artistic but impractical.', { analytical: -1, creative: 2, problem_solving: -1, social: -1, hands_on: 0 }),
      ]),
      createStep(2, 'Your design will influence global architecture practice.', 'How do you use this influence?', [
        createChoice('c1', 'Focus on aesthetics and personal expression', 'Narcissistic approach.', { analytical: -1, creative: 1, problem_solving: -1, social: -1, hands_on: 0 }),
        createChoice('c2', 'Demonstrate how beauty, sustainability, and function can integrate for societal benefit', 'Transformational thinking.', { analytical: 2, creative: 2, problem_solving: 2, social: 2, hands_on: 1 }),
        createChoice('c3', 'Push extreme boundaries to maximize artistic impact', 'Limits practical adoption.', { analytical: -1, creative: 2, problem_solving: -1, social: -1, hands_on: 1 }),
      ]),
      createStep(3, 'Reflecting on your career, what impact do you want architecture to have?', 'What\'s your legacy?', [
        createChoice('c1', 'Be remembered for beautiful iconic buildings', 'Limited vision.', { analytical: -1, creative: 1, problem_solving: -1, social: -1, hands_on: 0 }),
        createChoice('c2', 'Transform how architecture serves humanity—sustainability, equity, beauty, and innovation', 'Transformational legacy.', { analytical: 2, creative: 2, problem_solving: 2, social: 2, hands_on: 1 }),
        createChoice('c3', 'Achieve personal success and recognition', 'Self-focused.', { analytical: -1, creative: 0, problem_solving: -1, social: -1, hands_on: 0 }),
      ]),
    ],
    minMasteryScore: 75,
    estimatedTime: 14,
  },
  min_mastery_score: 75,
  estimated_time_minutes: 14,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const allQuizTemplates: QuizTemplate[] = [
  // Software Engineer (5 levels)
  softwareEngineer_L1,
  softwareEngineer_L2,
  softwareEngineer_L3,
  softwareEngineer_L4,
  softwareEngineer_L5,
  // Nurse (5 levels)
  nurse_L1,
  nurse_L2,
  nurse_L3,
  nurse_L4,
  nurse_L5,
  // Architect (5 levels)
  architect_L1,
  architect_L2,
  architect_L3,
  architect_L4,
  architect_L5,
];
